openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Wiki Pages API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: Represents an individual page in a project's wiki.
  name: Wiki Pages
paths:
  /api/v3/wiki_pages/{id}:
    get:
      parameters:
      - description: Wiki page identifier
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _embedded:
                      project:
                        _type: Project...
                        id: 12
                    _links:
                      addAttachment:
                        href: /api/v3/wiki_pages/72/attachments
                        method: post
                      attachments:
                        href: /api/v3/wiki_pages/72/attachments
                      project:
                        href: /api/v3/projects/12
                        title: some project
                      self:
                        href: /api/v3/wiki_pages/72
                    _type: WikiPage
                    id: 72
                    title: A wiki page with a name
              schema:
                $ref: '#/components/schemas/Wiki_PageModel'
          description: OK
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The requested resource could not be found.
          description: 'Returned if the wiki page does not exist or the client does not have sufficient permissions to see it.


            **Required permission:** view wiki page in the page''s project'
          headers: {}
      tags:
      - Wiki Pages
      description: Retrieve an individual wiki page as identified by the id parameter
      operationId: View_Wiki_Page
      summary: View Wiki Page
components:
  schemas:
    Link:
      type: object
      required:
      - href
      properties:
        href:
          type:
          - string
          - 'null'
          description: URL to the referenced resource (might be relative)
        title:
          type: string
          description: Representative label for the resource
        templated:
          type: boolean
          default: false
          description: If true the href contains parts that need to be replaced by the client
        method:
          type: string
          default: GET
          description: The HTTP verb to use when requesting the resource
        payload:
          type: object
          description: The payload to send in the request to achieve the desired result
        identifier:
          type: string
          description: An optional unique identifier to the link object
        type:
          type: string
          description: The MIME-Type of the returned resource.
      example:
        href: /api/v3/work_packages
        method: POST
    Wiki_PageModel:
      type: object
      required:
      - title
      properties:
        id:
          type: integer
          description: Identifier of this wiki page
          readOnly: true
          exclusiveMinimum: 0
        title:
          type: string
          description: The wiki page's title
        _links:
          type: object
          properties:
            addAttachment:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'Attach a file to the wiki page


                  # Conditions


                  **Permission**: edit wiki page'
                readOnly: true
      example:
        _type: WikiPage
        id: 72
        title: A wiki page with a name
        _embedded:
          project:
            _type: Project...
            id: 12
        _links:
          self:
            href: /api/v3/wiki_pages/72
          attachments:
            href: /api/v3/wiki_pages/72/attachments
          addAttachment:
            href: /api/v3/wiki_pages/72/attachments
            method: post
          project:
            href: /api/v3/projects/12
            title: some project
    ErrorResponse:
      type: object
      required:
      - _type
      - errorIdentifier
      - message
      properties:
        _embedded:
          type: object
          properties:
            details:
              type: object
              properties:
                attribute:
                  type: string
                  example: project
        _type:
          type: string
          enum:
          - Error
        errorIdentifier:
          type: string
          example: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
        message:
          type: string
          example: Project can't be blank.
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
