openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Help texts API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: The help texts endpoints return collections or single entities of type `HelpText`.
  name: Help texts
paths:
  /api/v3/help_texts:
    get:
      summary: List help texts
      operationId: list_help_texts
      tags:
      - Help texts
      description: List the complete collection of help texts.
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/HelpTextCollectionModel'
  /api/v3/help_texts/{id}:
    get:
      summary: Get help text
      operationId: get_help_text
      tags:
      - Help texts
      description: Fetches the help text from the given id.
      parameters:
      - name: id
        description: Help text id
        example: 1
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/HelpTextModel'
        '404':
          description: Returned if the help text does not exist.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                _type: Error
                errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                message: The requested resource could not be found.
components:
  schemas:
    CollectionLinks:
      type: object
      required:
      - self
      properties:
        self:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: 'This collection resource.


              **Resource**: Collection'
    Link:
      type: object
      required:
      - href
      properties:
        href:
          type:
          - string
          - 'null'
          description: URL to the referenced resource (might be relative)
        title:
          type: string
          description: Representative label for the resource
        templated:
          type: boolean
          default: false
          description: If true the href contains parts that need to be replaced by the client
        method:
          type: string
          default: GET
          description: The HTTP verb to use when requesting the resource
        payload:
          type: object
          description: The payload to send in the request to achieve the desired result
        identifier:
          type: string
          description: An optional unique identifier to the link object
        type:
          type: string
          description: The MIME-Type of the returned resource.
      example:
        href: /api/v3/work_packages
        method: POST
    CollectionModel:
      type: object
      required:
      - _type
      - total
      - count
      - _links
      properties:
        _type:
          type: string
          enum:
          - Collection
        total:
          type: integer
          description: The total amount of elements available in the collection.
          minimum: 0
        count:
          type: integer
          description: Actual amount of elements in this response.
          minimum: 0
        _links:
          $ref: '#/components/schemas/CollectionLinks'
    Formattable:
      type: object
      required:
      - format
      properties:
        format:
          type: string
          enum:
          - plain
          - markdown
          - custom
          readOnly: true
          description: Indicates the formatting language of the raw text
          example: markdown
        raw:
          type: string
          description: The raw text, as entered by the user
          example: I **am** formatted!
        html:
          type: string
          readOnly: true
          description: The text converted to HTML according to the format
          example: I <strong>am</strong> formatted!
      example:
        format: markdown
        raw: I am formatted!
        html: I am formatted!
    HelpTextModel:
      type: object
      required:
      - _type
      - id
      - attribute
      - scope
      - helpText
      - _links
      properties:
        _type:
          type: string
          enum:
          - HelpText
        id:
          type: integer
          format: int64
          minimum: 1
        attribute:
          type: string
          description: The attribute the help text is assigned to.
        scope:
          type: string
          enum:
          - WorkPackage
          - Project
        helpText:
          $ref: '#/components/schemas/Formattable'
        _links:
          type: object
          required:
          - self
          - editText
          - attachments
          - addAttachment
          properties:
            self:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'This help text resource.


                  **Resource**: HelpText'
            editText:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'Edit the help text entry.


                  **Resource**: text/html'
            attachments:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The attachment collection of this help text.


                  **Resource**: AttachmentCollection'
            addAttachment:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: Add an attachment to the help text.
      example:
        _type: HelpText
        id: 1
        attribute: id
        scope: WorkPackage
        caption: Some plain text caption
        helpText:
          format: markdown
          raw: Help text for id attribute.
          html: <p>Help text for id attribute.</p>
        _links:
          self:
            href: /api/v3/help_texts/1
          editText:
            href: /admin/attribute_help_texts/1/edit
            type: text/html
          attachments:
            href: /api/v3/help_texts/1/attachments
          addAttachment:
            href: /api/v3/help_texts/1/attachments
            method: post
    HelpTextCollectionModel:
      allOf:
      - $ref: '#/components/schemas/CollectionModel'
      - type: object
        required:
        - _links
        - _embedded
        properties:
          _links:
            type: object
            required:
            - self
            properties:
              self:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'This help text collection


                    **Resource**: HelpTextCollectionModel'
          _embedded:
            type: object
            required:
            - elements
            properties:
              elements:
                type: array
                items:
                  $ref: '#/components/schemas/HelpTextModel'
      example:
        total: 2
        count: 2
        _type: Collection
        _embedded:
          elements:
          - _type: HelpText
            _links:
              self:
                href: /api/v3/help_texts/1
              editText:
                href: /admin/attribute_help_texts/1/edit
                type: text/html
              attachments:
                href: /api/v3/help_texts/1/attachments
              addAttachment:
                href: /api/v3/help_texts/1/attachments
                method: post
            id: 1
            attribute: id
            attributeCaption: ID
            scope: WorkPackage
            helpText:
              format: markdown
              raw: Help text for id attribute.
              html: <p>Help text for id attribute.</p>
          - _type: HelpText
            _links:
              self:
                href: /api/v3/help_texts/2
              editText:
                href: /admin/attribute_help_texts/2/edit
                type: text/html
              attachments:
                href: /api/v3/help_texts/2/attachments
              addAttachment:
                href: /api/v3/help_texts/2/attachments
                method: post
            id: 2
            attribute: status
            attributeCaption: Status
            scope: WorkPackage
            helpText:
              format: markdown
              raw: Help text for status attribute.
              html: <p>Help text for status attribute.</p>
        _links:
          self:
            href: /api/v3/help_texts
    ErrorResponse:
      type: object
      required:
      - _type
      - errorIdentifier
      - message
      properties:
        _embedded:
          type: object
          properties:
            details:
              type: object
              properties:
                attribute:
                  type: string
                  example: project
        _type:
          type: string
          enum:
          - Error
        errorIdentifier:
          type: string
          example: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
        message:
          type: string
          example: Project can't be blank.
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
