openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Budgets API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: '*Note: Budgets are currently only implemented as a stub.'
  name: Budgets
paths:
  /api/v3/budgets/{id}:
    get:
      parameters:
      - description: Budget id
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _links:
                      self:
                        href: /api/v3/budgets/1
                        title: Q3 2015
                    _type: Budget
                    id: 1
                    subject: Q3 2015
              schema:
                $ref: '#/components/schemas/BudgetModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:MissingPermission
                    message: You are not allowed to see this budget.
          description: 'Returned if the client does not have sufficient permissions.


            **Required permission:** view work packages **or** view budgets (on the budgets project)'
          headers: {}
      tags:
      - Budgets
      description: ''
      operationId: view_Budget
      summary: view Budget
  /api/v3/projects/{id}/budgets:
    get:
      parameters:
      - description: Project id
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _embedded:
                      elements:
                      - _links:
                          self:
                            href: /api/v3/budgets/1
                            title: Q3 2015
                        _type: Budget
                        id: 1
                        subject: Q3 2015
                      - _links:
                          self:
                            href: /api/v3/budgets/2
                            title: Q4 2015
                        _type: Budget
                        id: 2
                        subject: Q4 2015
                    _links:
                      self:
                        href: /api/v3/projects/1/budgets
                    _type: Collection
                    count: 2
                    total: 2
              schema:
                $ref: '#/components/schemas/Budgets_by_ProjectModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:MissingPermission
                    message: You are not allowed to see the budgets of this project.
          description: 'Returned if the client does not have sufficient permissions to see the budgets of the given

            project.


            **Required permission:** view work packages **or** view budgets


            *Note that you will only receive this error, if you are at least allowed to see the corresponding project.*'
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The specified project does not exist.
          description: 'Returned if either:


            * the project does not exist


            * the client does not have sufficient permissions to see the project


            * the costs module is not enabled on the given project


            **Required permission:** view project


            *Note: A client without sufficient permissions shall not be able to test for the existence of a project.

            That''s why a 404 is returned here, even if a 403 might be more appropriate.*'
          headers: {}
      tags:
      - Budgets
      description: ''
      operationId: view_Budgets_of_a_Project
      summary: view Budgets of a Project
components:
  schemas:
    BudgetModel:
      type: object
      properties:
        _links:
          type: object
          required:
          - self
          properties:
            self:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'This budget


                  **Resource**: Budget'
                readOnly: true
      example:
        _type: Budget
        _links:
          self:
            href: /api/v3/budgets/1
            title: Q3 2015
        id: 1
        subject: Q3 2015
    Link:
      type: object
      required:
      - href
      properties:
        href:
          type:
          - string
          - 'null'
          description: URL to the referenced resource (might be relative)
        title:
          type: string
          description: Representative label for the resource
        templated:
          type: boolean
          default: false
          description: If true the href contains parts that need to be replaced by the client
        method:
          type: string
          default: GET
          description: The HTTP verb to use when requesting the resource
        payload:
          type: object
          description: The payload to send in the request to achieve the desired result
        identifier:
          type: string
          description: An optional unique identifier to the link object
        type:
          type: string
          description: The MIME-Type of the returned resource.
      example:
        href: /api/v3/work_packages
        method: POST
    ErrorResponse:
      type: object
      required:
      - _type
      - errorIdentifier
      - message
      properties:
        _embedded:
          type: object
          properties:
            details:
              type: object
              properties:
                attribute:
                  type: string
                  example: project
        _type:
          type: string
          enum:
          - Error
        errorIdentifier:
          type: string
          example: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
        message:
          type: string
          example: Project can't be blank.
    Budgets_by_ProjectModel:
      type: object
      example:
        _links:
          self:
            href: /api/v3/projects/1/budgets
        _type: Collection
        total: 2
        count: 2
        _embedded:
          elements:
          - _type: Budget
            _links:
              self:
                href: /api/v3/budgets/1
                title: Q3 2015
            id: 1
            subject: Q3 2015
          - _type: Budget
            _links:
              self:
                href: /api/v3/budgets/2
                title: Q4 2015
            id: 2
            subject: Q4 2015
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
