openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Types API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: Work package types represented in the system.
  name: Types
paths:
  /api/v3/projects/{id}/types:
    get:
      parameters:
      - description: ID of the project whose types will be listed
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _embedded:
                      elements:
                      - _links:
                          self:
                            href: /api/v3/types/1
                        _type: Type
                        color: '#ff0000'
                        createdAt: '2014-05-21T08:51:20.396Z'
                        id: 1
                        isDefault: true
                        isMilestone: false
                        name: Bug
                        position: 1
                        updatedAt: '2014-05-21T08:51:20.396Z'
                      - _links:
                          self:
                            href: /api/v3/types/2
                        _type: Type
                        color: '#888'
                        createdAt: '2014-05-21T08:51:20.396Z'
                        id: 2
                        isDefault: false
                        isMilestone: false
                        name: Feature
                        position: 2
                        updatedAt: '2014-05-21T08:51:20.396Z'
                    _links:
                      self:
                        href: /api/v3/projects/11/types
                    _type: Collection
                    count: 2
                    total: 2
              schema:
                $ref: '#/components/schemas/Types_by_WorkspaceModel'
          description: OK
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The specified project does not exist.
          description: 'Returned if the project does not exist or the client does not have sufficient permissions

            to see it.


            **Required permission:** view work packages **or** manage types (on given project)


            *Note: A client without sufficient permissions shall not be able to test for the existence of a project.

            That''s why a 404 is returned here, even if a 403 might be more appropriate.*'
          headers: {}
      tags:
      - Types
      description: 'This endpoint lists the types that are *available* in a given project.

        This endpoint is deprecated and replaced by `/api/v3/workspaces/{id}/types`'
      operationId: List_types_available_in_a_project
      summary: List types available in a project
  /api/v3/types:
    get:
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _embedded:
                      elements:
                      - _links:
                          self:
                            href: /api/v3/types/1
                        _type: Type
                        color: '#ff0000'
                        createdAt: '2014-05-21T08:51:20.396Z'
                        id: 1
                        isDefault: true
                        isMilestone: false
                        name: Bug
                        position: 1
                        updatedAt: '2014-05-21T08:51:20.396Z'
                      - _links:
                          self:
                            href: /api/v3/types/2
                        _type: Type
                        color: '#888'
                        createdAt: '2014-05-21T08:51:20.396Z'
                        id: 2
                        isDefault: false
                        isMilestone: false
                        name: Feature
                        position: 2
                        updatedAt: '2014-05-21T08:51:20.396Z'
                    _links:
                      self:
                        href: /api/v3/types
                    _type: Collection
                    count: 2
                    total: 2
              schema:
                $ref: '#/components/schemas/TypesModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:MissingPermission
                    message: You are not allowed to see the types.
          description: 'Returned if the client does not have sufficient permissions.


            **Required permission:** view work package or manage types (on any project)'
          headers: {}
      tags:
      - Types
      description: ''
      operationId: List_all_Types
      summary: List all Types
  /api/v3/types/{id}:
    get:
      parameters:
      - description: Type id
        example: '1'
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _links:
                      self:
                        href: /api/v3/types/1
                    _type: Type
                    color: '#ff0000'
                    createdAt: '2014-05-21T08:51:20.396Z'
                    id: 1
                    isDefault: true
                    isMilestone: false
                    name: Bug
                    position: 1
                    updatedAt: '2014-05-21T08:51:20.396Z'
              schema:
                $ref: '#/components/schemas/TypeModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:MissingPermission
                    message: You are not allowed to see this type.
          description: 'Returned if the client does not have sufficient permissions.


            **Required permission:** view work package or manage types (on any project)'
          headers: {}
      tags:
      - Types
      description: ''
      operationId: View_Type
      summary: View Type
  /api/v3/workspaces/{id}/types:
    get:
      parameters:
      - description: ID of the workspace whose types will be listed
        example: '1'
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _embedded:
                      elements:
                      - _links:
                          self:
                            href: /api/v3/types/1
                        _type: Type
                        color: '#ff0000'
                        createdAt: '2014-05-21T08:51:20.396Z'
                        id: 1
                        isDefault: true
                        isMilestone: false
                        name: Bug
                        position: 1
                        updatedAt: '2014-05-21T08:51:20.396Z'
                      - _links:
                          self:
                            href: /api/v3/types/2
                        _type: Type
                        color: '#888'
                        createdAt: '2014-05-21T08:51:20.396Z'
                        id: 2
                        isDefault: false
                        isMilestone: false
                        name: Feature
                        position: 2
                        updatedAt: '2014-05-21T08:51:20.396Z'
                    _links:
                      self:
                        href: /api/v3/workspaces/11/types
                    _type: Collection
                    count: 2
                    total: 2
              schema:
                $ref: '#/components/schemas/Types_by_WorkspaceModel'
          description: OK
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The specified workspace does not exist.
          description: 'Returned if the workspace does not exist or the client does not have sufficient permissions

            to see it.


            **Required permission:** view work packages **or** manage types (on given workspace)


            *Note: A client without sufficient permissions shall not be able to test for the existence of a workspace.

            That''s why a 404 is returned here, even if a 403 might be more appropriate.*'
          headers: {}
      tags:
      - Types
      description: This endpoint lists the types that are *available* in a given workspace.
      operationId: List_types_available_in_a_workspace
      summary: List types available in a workspace
components:
  schemas:
    CollectionLinks:
      type: object
      required:
      - self
      properties:
        self:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: 'This collection resource.


              **Resource**: Collection'
    Link:
      type: object
      required:
      - href
      properties:
        href:
          type:
          - string
          - 'null'
          description: URL to the referenced resource (might be relative)
        title:
          type: string
          description: Representative label for the resource
        templated:
          type: boolean
          default: false
          description: If true the href contains parts that need to be replaced by the client
        method:
          type: string
          default: GET
          description: The HTTP verb to use when requesting the resource
        payload:
          type: object
          description: The payload to send in the request to achieve the desired result
        identifier:
          type: string
          description: An optional unique identifier to the link object
        type:
          type: string
          description: The MIME-Type of the returned resource.
      example:
        href: /api/v3/work_packages
        method: POST
    TypesModel:
      type: object
      example:
        _links:
          self:
            href: /api/v3/types
        total: 2
        count: 2
        _type: Collection
        _embedded:
          elements:
          - _links:
              self:
                href: /api/v3/types/1
            _type: Type
            id: 1
            name: Bug
            color: '#ff0000'
            position: 1
            isDefault: true
            isMilestone: false
            createdAt: '2014-05-21T08:51:20.429Z'
            updatedAt: '2014-05-21T08:51:20.429Z'
          - _links:
              self:
                href: /api/v3/types/2
            _type: Type
            id: 2
            name: Feature
            color: '#888'
            position: 2
            isDefault: false
            isMilestone: false
            createdAt: '2014-05-21T08:51:20.429Z'
            updatedAt: '2014-05-21T08:51:20.429Z'
    CollectionModel:
      type: object
      required:
      - _type
      - total
      - count
      - _links
      properties:
        _type:
          type: string
          enum:
          - Collection
        total:
          type: integer
          description: The total amount of elements available in the collection.
          minimum: 0
        count:
          type: integer
          description: Actual amount of elements in this response.
          minimum: 0
        _links:
          $ref: '#/components/schemas/CollectionLinks'
    Types_by_WorkspaceModel:
      allOf:
      - $ref: '#/components/schemas/CollectionModel'
      - type: object
        required:
        - _links
        - _embedded
        properties:
          _links:
            type: object
            required:
            - self
            properties:
              self:
                allOf:
                - $ref: '#/components/schemas/Link'
                - description: 'The types collection


                    **Resource**: TypesCollection'
                  readOnly: true
          _embedded:
            type: object
            properties:
              elements:
                type: array
                readOnly: true
                items:
                  allOf:
                  - $ref: '#/components/schemas/TypeModel'
                  - description: Collection of Types
    ErrorResponse:
      type: object
      required:
      - _type
      - errorIdentifier
      - message
      properties:
        _embedded:
          type: object
          properties:
            details:
              type: object
              properties:
                attribute:
                  type: string
                  example: project
        _type:
          type: string
          enum:
          - Error
        errorIdentifier:
          type: string
          example: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
        message:
          type: string
          example: Project can't be blank.
    TypeModel:
      type: object
      required:
      - id
      - name
      - color
      - position
      - isDefault
      - isMilestone
      - createdAt
      - updatedAt
      properties:
        id:
          type: integer
          description: Type id
          readOnly: true
          exclusiveMinimum: 0
        name:
          type: string
          description: Type name
          readOnly: true
        color:
          type:
          - string
          - 'null'
          description: The color used to represent this type
          readOnly: true
        position:
          type: integer
          description: Sort index of the type
          readOnly: true
        isDefault:
          type: boolean
          description: Is this type active by default in new projects?
          readOnly: true
        isMilestone:
          type: boolean
          description: Do work packages of this type represent a milestone?
          readOnly: true
        createdAt:
          type: string
          format: date-time
          description: Time of creation
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          description: Time of the most recent change to the user
        _links:
          type: object
          required:
          - self
          properties:
            self:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'This type


                  **Resource**: Type'
                readOnly: true
      example:
        _links:
          self:
            href: /api/v3/types/1
        _type: Type
        id: 1
        name: Bug
        color: '#ff0000'
        position: 1
        isDefault: true
        isMilestone: false
        createdAt: '2014-05-21T08:51:20.624Z'
        updatedAt: '2014-05-21T08:51:20.624Z'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
