openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Priorities API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: The priorities endpoints return collections or single entities of type `Priority`.
  name: Priorities
paths:
  /api/v3/priorities:
    get:
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                simple priority collection:
                  $ref: '#/components/examples/PriorityCollection'
              schema:
                $ref: '#/components/schemas/PriorityCollectionModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:MissingPermission
                    message: You are not allowed to see the priorities.
          description: 'Returned if the client does not have sufficient permissions.


            **Required permission:** view work package (on any project)'
          headers: {}
      tags:
      - Priorities
      description: ''
      operationId: List_all_Priorities
      summary: List all Priorities
  /api/v3/priorities/{id}:
    get:
      parameters:
      - description: Priority id
        example: 1
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _links:
                      self:
                        href: /api/v3/priorities/1
                        title: Low
                    _type: Priority
                    id: 1
                    isActive: true
                    isDefault: false
                    name: Low
                    position: 1
              schema:
                $ref: '#/components/schemas/PriorityModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:MissingPermission
                    message: You are not allowed to see this priority.
          description: 'Returned if the client does not have sufficient permissions.


            **Required permission:** view work package (on any project)'
          headers: {}
      tags:
      - Priorities
      description: ''
      operationId: View_Priority
      summary: View Priority
components:
  schemas:
    PriorityModel:
      type: object
      properties:
        id:
          type: integer
          description: Priority id
          readOnly: true
          exclusiveMinimum: 0
        name:
          type: string
          description: Priority name
          readOnly: true
          minLength: 1
        position:
          type: integer
          description: Sort index of the priority
          readOnly: true
          exclusiveMinimum: 0
        isDefault:
          type: boolean
          description: Indicates whether this is the default value
          readOnly: true
        isActive:
          type: boolean
          description: Indicates whether the priority is available
        _links:
          type: object
          required:
          - self
          properties:
            self:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'This priority


                  **Resource**: Priority'
                readOnly: true
      example:
        _type: Priority
        _links:
          self:
            href: /api/v3/priorities/1
            title: Low
        id: 1
        name: Low
        position: 1
        isDefault: false
        isActive: true
    Link:
      type: object
      required:
      - href
      properties:
        href:
          type:
          - string
          - 'null'
          description: URL to the referenced resource (might be relative)
        title:
          type: string
          description: Representative label for the resource
        templated:
          type: boolean
          default: false
          description: If true the href contains parts that need to be replaced by the client
        method:
          type: string
          default: GET
          description: The HTTP verb to use when requesting the resource
        payload:
          type: object
          description: The payload to send in the request to achieve the desired result
        identifier:
          type: string
          description: An optional unique identifier to the link object
        type:
          type: string
          description: The MIME-Type of the returned resource.
      example:
        href: /api/v3/work_packages
        method: POST
    CollectionLinks:
      type: object
      required:
      - self
      properties:
        self:
          allOf:
          - $ref: '#/components/schemas/Link'
          - description: 'This collection resource.


              **Resource**: Collection'
    PriorityCollectionModel:
      allOf:
      - $ref: '#/components/schemas/CollectionModel'
      - type: object
        required:
        - _links
        - _embedded
        properties:
          _links:
            type: object
            required:
            - self
            properties:
              self:
                allOf:
                - $ref: '#/components/schemas/Link'
                - properties:
                    self:
                      allOf:
                      - $ref: '#/components/schemas/Link'
                      - description: 'This priority collection


                          **Resource**: PriorityCollectionModel'
                readOnly: true
          _embedded:
            type: object
            required:
            - elements
            properties:
              elements:
                type: array
                items:
                  $ref: '#/components/schemas/PriorityModel'
    CollectionModel:
      type: object
      required:
      - _type
      - total
      - count
      - _links
      properties:
        _type:
          type: string
          enum:
          - Collection
        total:
          type: integer
          description: The total amount of elements available in the collection.
          minimum: 0
        count:
          type: integer
          description: Actual amount of elements in this response.
          minimum: 0
        _links:
          $ref: '#/components/schemas/CollectionLinks'
    ErrorResponse:
      type: object
      required:
      - _type
      - errorIdentifier
      - message
      properties:
        _embedded:
          type: object
          properties:
            details:
              type: object
              properties:
                attribute:
                  type: string
                  example: project
        _type:
          type: string
          enum:
          - Error
        errorIdentifier:
          type: string
          example: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
        message:
          type: string
          example: Project can't be blank.
  examples:
    PriorityCollection:
      value:
        _embedded:
          elements:
          - _links:
              self:
                href: /api/v3/priorities/1
                title: Low
            _type: Priority
            id: 1
            isActive: true
            isDefault: false
            name: Low
            position: 1
          - _links:
              self:
                href: /api/v3/priorities/2
                title: Normal
            _type: Priority
            id: 2
            isActive: true
            isDefault: true
            name: Normal
            position: 2
          - _links:
              self:
                href: /api/v3/priorities/3
                title: High
            _type: Priority
            id: 3
            isActive: true
            isDefault: false
            name: High
            position: 3
          - _links:
              self:
                href: /api/v3/priorities/4
                title: Immediate
            _type: Priority
            id: 4
            isActive: true
            isDefault: false
            name: Immediate
            position: 5
        _links:
          self:
            href: /api/v3/priorities
        _type: Collection
        count: 4
        total: 4
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
