openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Actions & Capabilities API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: An action is a change one can trigger within the OpenProject instance.
  name: Actions & Capabilities
paths:
  /api/v3/actions:
    get:
      parameters:
      - description: 'JSON specifying filter conditions.

          Accepts the same format as returned by the [queries](https://www.openproject.org/docs/api/endpoints/queries/) endpoint.

          Currently supported filters are:


          + id: Returns only the action having the id or all actions except those having the id(s).'
        example: '[{ "id": { "operator": "=", "values": ["memberships/create"] }" }]'
        in: query
        name: filters
        required: false
        schema:
          type: string
      - description: 'JSON specifying sort criteria.

          Accepts the same format as returned by the [queries](https://www.openproject.org/docs/api/endpoints/queries/) endpoint. Currently supported sorts are:


          + *No sort supported yet*'
        example: '[["id", "asc"]]'
        in: query
        name: sortBy
        required: false
        schema:
          default: '[["id", "asc"]]'
          type: string
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _embedded:
                      elements:
                      - _links:
                          self:
                            href: /api/v3/actions/work_packages/create
                            title: Add work package
                        _type: Action
                        description: Creating a work package within a project including the uploading of attachments. Some attributes might not be selected, e.g version which requires a second permission
                        id: work_packages/create
                        modules:
                        - work_packages
                        name: Add work package
                      - _links:
                          self:
                            href: /api/v3/actions/work_packages/assign_versions
                            title: Assigning version
                        _type: Action
                        description: Assigning a work package to a version when creating/updating a work package. Only principals having this permission can assign a value to the version property of the work package resource.
                        id: work_packages/assign_versions
                        modules:
                        - work_packages
                        - versions
                        name: Assign version
                    _links:
                      self:
                        href: /api/v3/actions
                    _type: Collection
                    count: 2
                    total: 2
              schema:
                $ref: '#/components/schemas/List_actionsModel'
          description: OK
          headers: {}
      tags:
      - Actions & Capabilities
      description: 'Returns a collection of actions. The client can choose to filter the actions similar to how work packages are filtered.

        In addition to the provided filters, the server will reduce the result set to only contain actions, for which the requesting client

        has sufficient permissions.'
      operationId: List_actions
      summary: List actions
  /api/v3/actions/{id}:
    get:
      parameters:
      - description: action id which is the name of the action
        example: work_packages/create
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _links:
                      self:
                        href: /api/v3/actions/work_packages/create
                        title: Add work package
                    _type: Action
                    description: Creating a work package within a project including the uploading of attachments. Some attributes might not be selected, e.g version which requires a second permission
                    id: work_packages/create
                    modules:
                    - work_packages
                    name: Add work package
              schema:
                $ref: '#/components/schemas/View_actionModel'
          description: OK
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The requested resource could not be found.
          description: Returned if the action does not exist.
          headers: {}
      tags:
      - Actions & Capabilities
      description: Returns an individual action.
      operationId: View_action
      summary: View action
  /api/v3/capabilities:
    get:
      parameters:
      - description: "JSON specifying filter conditions.\nAccepts the same format as returned by the [queries](https://www.openproject.org/docs/api/endpoints/queries/) endpoint.\n\n+ action: Get all capabilities of a certain action\n\n+ principal: Get all capabilities of a principal\n\n+ context: Get all capabilities within a context. Note that for a workspace context the client needs to\n  provide `w{id}`, e.g. `w5` and for the global context a `g`.\n\n  + **Deprecation**: The now deprecated context `p` for project still works, but must eventually be replaced\n    with the `w` for the workspace context."
        example: '[{ "principal": { "operator": "=", "values": ["1"] }" }]'
        in: query
        name: filters
        required: false
        schema:
          type: string
      - description: 'JSON specifying sort criteria.

          Accepts the same format as returned by the [queries](https://www.openproject.org/docs/api/endpoints/queries/) endpoint. Currently supported sorts are:


          + id: Sort by the capabilities id'
        example: '[["id", "asc"]]'
        in: query
        name: sortBy
        required: false
        schema:
          default: '[["id", "asc"]]'
          type: string
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _embedded:
                      elements:
                      - _links:
                          action:
                            href: /api/v3/actions/work_packages/create
                            title: Add work package
                          context:
                            href: /api/v3/projects/123
                            title: A project
                          principal:
                            href: /api/v3/users/567
                            title: Some user
                          self:
                            href: /api/v3/capabilities/work_packages/create/w123-567
                        _type: Capability
                        id: work_packages/create/w123-567
                      - _links:
                          action:
                            href: /api/v3/actions/work_packages/assignee
                          context:
                            href: /api/v3/projects/123
                            title: A project
                          principal:
                            href: /api/v3/users/567
                            title: Some user
                          self:
                            href: /api/v3/capabilities/work_packages/assignee/w123-567
                        _type: Capability
                        id: work_packages/assignee/w123-567
                      - _links:
                          action:
                            href: /api/v3/actions/memberships/create
                          context:
                            href: /api/v3/portfolios/345
                            title: A portfolio
                          principal:
                            href: /api/v3/users/821
                            title: Some user
                          self:
                            href: /api/v3/capabilities/memberships/create/w345-821
                            title: Create members
                        _type: Capability
                        id: memberships/create/w345-821
                      - _links:
                          context:
                            href: /api/v3/capabilities/context/global
                            title: Global
                          principal:
                            href: /api/v3/users/567
                            title: Some user
                          self:
                            href: /api/v3/capabilities/users/delete/g-567
                            title: Delete user
                        _type: Capability
                        id: users/delete/g-567
                    _links:
                      changeSize:
                        href: /api/v3/capabilities?pageSize={size}
                        templated: true
                      jumpTo:
                        href: /api/v3/capabilities?offset={offset}
                        templated: true
                      self:
                        href: /api/v3/capabilities
                    _type: Collection
                    count: 4
                    total: 4
              schema:
                $ref: '#/components/schemas/List_capabilitiesModel'
          description: OK
          headers: {}
      tags:
      - Actions & Capabilities
      description: Returns a collection of actions assigned to a principal in a context. The client can choose to filter the actions similar to how work packages are filtered. In addition to the provided filters, the server will reduce the result set to only contain actions, for which the requesting client has sufficient permissions
      operationId: List_capabilities
      summary: List capabilities
  /api/v3/capabilities/context/global:
    get:
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _links:
                      self:
                        href: /api/v3/capabilities/context/global
                    _type: CapabilityContext::Global
                    id: global
              schema:
                $ref: '#/components/schemas/View_global_contextModel'
          description: OK
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The requested resource could not be found.
          description: Returned if the action does not exist.
          headers: {}
      tags:
      - Actions & Capabilities
      description: Returns the global capability context. This context is necessary to consistently link to a context even if the context is not a project.
      operationId: View_global_context
      summary: View global context
  /api/v3/capabilities/{id}:
    get:
      parameters:
      - description: capability id
        example: work_packages/create/p123-567
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _links:
                      action:
                        href: /api/v3/actions/work_packages/create
                        title: Add work package
                      context:
                        href: /api/v3/projects/123
                        title: A project
                      principal:
                        href: /api/v3/users/567
                        title: Some user
                      self:
                        href: /api/v3/capabilities/work_packages/create/w123-567
                    _type: Capability
                    id: work_packages/create/p123-567
              schema:
                $ref: '#/components/schemas/View_capabilitiesModel'
          description: OK
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The requested resource could not be found.
          description: Returned if the capability does not exist.
          headers: {}
      tags:
      - Actions & Capabilities
      description: ''
      operationId: View_capabilities
      summary: View capabilities
components:
  schemas:
    List_actionsModel:
      type: object
      example:
        _links:
          self:
            href: /api/v3/actions
        total: 2
        count: 2
        _type: Collection
        _embedded:
          elements:
          - _links:
              self:
                href: /api/v3/actions/work_packages/create
                title: Add work package
            _type: Action
            id: work_packages/create
            name: Add work package
            description: Creating a work package within a project including the uploading of attachments. Some attributes might not be selected, e.g version which requires a second permission
            modules:
            - work_packages
          - _links:
              self:
                href: /api/v3/actions/work_packages/assign_versions
                title: Assigning version
            _type: Action
            id: work_packages/assign_versions
            name: Assign version
            description: Assigning a work package to a version when creating/updating a work package. Only principals having this permission can assign a value to the version property of the work package resource.
            modules:
            - work_packages
            - versions
    View_actionModel:
      type: object
      example:
        _links:
          self:
            href: /api/v3/actions/work_packages/create
            title: Add work package
        _type: Action
        id: work_packages/create
        name: Add work package
        description: Creating a work package within a project including the uploading of attachments. Some attributes might not be selected, e.g version which requires a second permission
        modules:
        - work_packages
    View_capabilitiesModel:
      type: object
      example:
        _links:
          self:
            href: /api/v3/capabilities/work_packages/create/p123-567
          action:
            href: /api/v3/actions/work_packages/create
            title: Add work package
          context:
            href: /api/v3/projects/123
            title: A project
          principal:
            href: /api/v3/users/567
            title: Some user
        _type: Capability
        id: work_packages/create/p123-567
    View_global_contextModel:
      type: object
      example:
        _links:
          self:
            href: /api/v3/capabilities/context/global
        _type: CapabilityContext::Global
        id: global
    List_capabilitiesModel:
      type: object
      example:
        _links:
          self:
            href: /api/v3/capabilities
          changeSize:
            href: /api/v3/capabilities?pageSize={size}
            templated: true
          jumpTo:
            href: /api/v3/capabilities?offset={offset}
            templated: true
        total: 4
        count: 4
        _type: Collection
        _embedded:
          elements:
          - _links:
              self:
                href: /api/v3/capabilities/work_packages/create/p123-567
              action:
                href: /api/v3/actions/work_packages/create
                title: Add work package
              context:
                href: /api/v3/projects/123
                title: A project
              principal:
                href: /api/v3/users/567
                title: Some user
            _type: Capability
            id: work_packages/create/p123-567
          - _links:
              self:
                href: /api/v3/capabilities/work_packages/assignee/p123-567
              action:
                href: /api/v3/actions/work_packages/assignee
              context:
                href: /api/v3/projects/123
                title: A project
              principal:
                href: /api/v3/users/567
                title: Some user
            _type: Capability
            id: work_packages/assignee/p123-567
          - _links:
              self:
                href: /api/v3/capabilities/memberships/create/p345-821
                title: Create members
              action:
                href: /api/v3/actions/memberships/create
              context:
                href: /api/v3/projects/345
                title: A project
              principal:
                href: /api/v3/users/821
                title: Some user
            _type: Capability
            id: memberships/create/p345-821
          - _links:
              self:
                href: /api/v3/capabilities/users/delete/g-567
                title: Delete user
              context:
                href: /api/v3/capabilities/context/global
                title: Global
              principal:
                href: /api/v3/users/567
                title: Some user
            _type: Capability
            id: users/delete/g-567
    ErrorResponse:
      type: object
      required:
      - _type
      - errorIdentifier
      - message
      properties:
        _embedded:
          type: object
          properties:
            details:
              type: object
              properties:
                attribute:
                  type: string
                  example: project
        _type:
          type: string
          enum:
          - Error
        errorIdentifier:
          type: string
          example: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
        message:
          type: string
          example: Project can't be blank.
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
