openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Collections API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: Whenever a client calls a resource that can return more than one element, it will receive a collection of elements.
  name: Collections
paths:
  /api/v3/examples:
    get:
      parameters:
      - description: 'The column to group by.

          Note: Aggregation is as of now only supported by the work package collection.

          You can pass any column name as returned by the [queries](https://www.openproject.org/docs/api/endpoints/queries/) endpoint.'
        example: status
        in: query
        name: groupBy
        required: false
        schema:
          type: string
      - description: ''
        example: true
        in: query
        name: showSums
        required: false
        schema:
          default: false
          type: boolean
      responses:
        '200':
          description: OK
          headers: {}
      tags:
      - Collections
      description: ''
      operationId: view_aggregated_result
      summary: view aggregated result
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
