openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Schemas API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: The schema provides detailed information about the properties of a resource.
  name: Schemas
paths:
  /api/v3/example/schema:
    get:
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _dependencies: []
                    _links:
                      self:
                        href: /api/v3/example/schema
                    _type: Schema
                    lockVersion:
                      name: Resource Version
                      type: Integer
                      writable: false
                    status:
                      _embedded:
                        allowedValues:
                        - _links:
                            self:
                              href: /api/v3/statuses/1
                          _type: Status
                          createdAt: '2014-05-21T08:51:20.396Z'
                          defaultDoneRatio: 0
                          id: 1
                          isClosed: false
                          isDefault: true
                          name: New
                          position: 1
                          updatedAt: '2014-05-21T09:12:00.441Z'
                        - _links:
                            self:
                              href: /api/v3/statuses/2
                          _type: Status
                          createdAt: '2014-05-21T08:51:20.396Z'
                          defaultDoneRatio: 100
                          id: 2
                          isClosed: true
                          isDefault: false
                          name: Closed
                          position: 2
                          updatedAt: '2014-05-21T09:12:00.441Z'
                      _links:
                        allowedValues:
                        - href: /api/v3/statuses/1
                          title: New
                        - href: /api/v3/statuses/2
                          title: Closed
                      location: _links
                      name: Status
                      type: Status
                    subject:
                      maxLength: 255
                      minLength: 1
                      name: Subject
                      type: String
              schema:
                $ref: '#/components/schemas/Example_SchemaModel'
          description: OK
          headers: {}
      tags:
      - Schemas
      description: This is an example of how a schema might look like. Note that this endpoint does not exist in the actual implementation.
      operationId: view_the_schema
      summary: view the schema
components:
  schemas:
    Example_SchemaModel:
      type: object
      example:
        _type: Schema
        _dependencies: []
        _links:
          self:
            href: /api/v3/example/schema
        lockVersion:
          name: Resource Version
          type: Integer
          writable: false
        subject:
          name: Subject
          type: String
          minLength: 1
          maxLength: 255
        status:
          _links:
            allowedValues:
            - href: /api/v3/statuses/1
              title: New
            - href: /api/v3/statuses/2
              title: Closed
          name: Status
          type: Status
          location: _links
          _embedded:
            allowedValues:
            - _links:
                self:
                  href: /api/v3/statuses/1
              _type: Status
              id: 1
              name: New
              position: 1
              isDefault: true
              isClosed: false
              defaultDoneRatio: 0
              createdAt: '2014-05-21T08:51:20.991Z'
              updatedAt: '2014-05-21T09:12:00.155Z'
            - _links:
                self:
                  href: /api/v3/statuses/2
              _type: Status
              id: 2
              name: Closed
              position: 2
              isDefault: false
              isClosed: true
              defaultDoneRatio: 100
              createdAt: '2014-05-21T08:51:20.991Z'
              updatedAt: '2014-05-21T09:12:00.155Z'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
