openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Query Columns API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: A QueryColumn can be referenced by a Query to denote the work package properties the client should display for the work packages returned as query results.
  name: Query Columns
paths:
  /api/v3/queries/columns/{id}:
    get:
      parameters:
      - description: QueryColumn id
        example: priority
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _links:
                      self:
                        href: /api/v3/queries/columns/priority
                        title: Priority
                    _type: QueryColumn::Property
                    id: priority
                    name: Priority
              schema:
                $ref: '#/components/schemas/Query_ColumnModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:Unauthenticated
                    message: You are not authorized to access this resource.
          description: 'Returned if the client does not have sufficient permissions to see it.


            **Required permission:** view work package in any project'
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The specified query does not exist.
          description: Returned if the QueryColumn does not exist.
          headers: {}
      tags:
      - Query Columns
      description: Retrieve an individual QueryColumn as identified by the `id` parameter.
      operationId: View_Query_Column
      summary: View Query Column
components:
  schemas:
    Query_ColumnModel:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: string
          description: Query column id
          readOnly: true
        name:
          type: string
          description: Query column name
      example:
        _type: QueryColumn::Property
        id: priority
        name: Priority
        _links:
          self:
            href: /api/v3/queries/columns/priority
            title: Priority
    ErrorResponse:
      type: object
      required:
      - _type
      - errorIdentifier
      - message
      properties:
        _embedded:
          type: object
          properties:
            details:
              type: object
              properties:
                attribute:
                  type: string
                  example: project
        _type:
          type: string
          enum:
          - Error
        errorIdentifier:
          type: string
          example: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
        message:
          type: string
          example: Project can't be blank.
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
