openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Query Sort Bys API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: A QuerySortBy can be referenced by a Query to denote the sorting applied to the query's work package results.
  name: Query Sort Bys
paths:
  /api/v3/queries/sort_bys/{id}:
    get:
      parameters:
      - description: QuerySortBy identifier. The identifier is a combination of the column identifier and the direction.
        example: status-asc
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/hal+json:
              examples:
                response:
                  value:
                    _links:
                      column:
                        href: /api/v3/queries/columns/status
                        title: Status
                      direction:
                        href: urn:openproject-org:api:v3:queries:directions:asc
                        title: Ascending
                      self:
                        href: /api/v3/queries/sort_bys/status-asc
                        title: Status (Ascending)
                    _type: QuerySortBy
                    id: status-asc
                    name: Status (Ascending)
              schema:
                $ref: '#/components/schemas/Query_Sort_ByModel'
          description: OK
          headers: {}
        '403':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:Unauthenticated
                    message: You are not authorized to access this resource.
          description: 'Returned if the client does not have sufficient permissions to see it.


            **Required permission:** view work package in any project'
          headers: {}
        '404':
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    _type: Error
                    errorIdentifier: urn:openproject-org:api:v3:errors:NotFound
                    message: The specified query does not exist.
          description: Returned if the QuerySortBy does not exist.
          headers: {}
      tags:
      - Query Sort Bys
      description: Retrieve an individual QuerySortBy as identified by the id parameter.
      operationId: View_Query_Sort_By
      summary: View Query Sort By
components:
  schemas:
    Query_Sort_ByModel:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: string
          description: QuerySortBy id
          readOnly: true
        name:
          type: string
          description: QuerySortBy name
      example:
        _type: QuerySortBy
        id: status-asc
        name: Status (Ascending)
        _links:
          self:
            href: /api/v3/queries/sort_bys/status-asc
            title: Status (Ascending)
          column:
            href: /api/v3/queries/columns/status
            title: Status
          direction:
            href: urn:openproject-org:api:v3:queries:directions:asc
            title: Ascending
    ErrorResponse:
      type: object
      required:
      - _type
      - errorIdentifier
      - message
      properties:
        _embedded:
          type: object
          properties:
            details:
              type: object
              properties:
                attribute:
                  type: string
                  example: project
        _type:
          type: string
          enum:
          - Error
        errorIdentifier:
          type: string
          example: urn:openproject-org:api:v3:errors:PropertyConstraintViolation
        message:
          type: string
          example: Project can't be blank.
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
