openapi: 3.2.0
info:
  description: You're looking at the current **stable** documentation of the OpenProject APIv3.
  title: OpenProject API V3 (Stable) Root API
  version: '3'
servers:
- url: https://qa.openproject-edge.com
  description: Edge QA instance
- url: https://qa.openproject-stage.com
  description: Staging instance
- url: https://community.openproject.org
  description: Community instance
security:
- BasicAuth: []
tags:
- description: The root resource contains links to available resources in the API.
  name: Root
paths:
  /api/v3:
    get:
      summary: View root
      operationId: view_root
      description: Returns the root resource, containing basic information about the server instance and a collection of useful links.
      tags:
      - Root
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/RootModel'
components:
  schemas:
    Link:
      type: object
      required:
      - href
      properties:
        href:
          type:
          - string
          - 'null'
          description: URL to the referenced resource (might be relative)
        title:
          type: string
          description: Representative label for the resource
        templated:
          type: boolean
          default: false
          description: If true the href contains parts that need to be replaced by the client
        method:
          type: string
          default: GET
          description: The HTTP verb to use when requesting the resource
        payload:
          type: object
          description: The payload to send in the request to achieve the desired result
        identifier:
          type: string
          description: An optional unique identifier to the link object
        type:
          type: string
          description: The MIME-Type of the returned resource.
      example:
        href: /api/v3/work_packages
        method: POST
    RootModel:
      type: object
      required:
      - _type
      - instanceName
      - _links
      properties:
        _type:
          type: string
          enum:
          - Root
        instanceName:
          type: string
          description: The name of the OpenProject instance
        coreVersion:
          type: string
          description: 'The OpenProject core version number for the instance


            # Conditions


            **Permission** requires admin privileges'
        _links:
          type: object
          required:
          - self
          - configuration
          - memberships
          - priorities
          - relations
          - statuses
          - time_entries
          - types
          - user
          - userPreferences
          - workPackages
          properties:
            self:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'This root information object.


                  **Resource**: Root'
            configuration:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The configuration resource.


                  **Resource**: Configuration'
            memberships:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The collection of memberships.


                  **Resource**: Collection'
            priorities:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The collection of priorities.


                  **Resource**: Collection'
            relations:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The collection of relations.


                  **Resource**: Collection'
            statuses:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The collection of statuses.


                  **Resource**: Collection'
            time_entries:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The collection of time entries.


                  **Resource**: Collection'
            types:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The collection of types.


                  **Resource**: Collection'
            user:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The current user resource.


                  **Resource**: User'
            userPreferences:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The current user preferences resource.


                  **Resource**: UserPreferences'
            workPackages:
              allOf:
              - $ref: '#/components/schemas/Link'
              - description: 'The work package collection.


                  **Resource**: Collection'
      example:
        _type: Root
        instanceName: OpenProject
        coreVersion: 12.1.0
        _links:
          self:
            href: /api/v3
          configuration:
            href: /api/v3/configuration
          memberships:
            href: /api/v3/memberships
          priorities:
            href: /api/v3/priorities
          relations:
            href: /api/v3/relations
          statuses:
            href: /api/v3/statuses
          time_entries:
            href: /api/v3/time_entries
          types:
            href: /api/v3/types
          user:
            href: /api/v3/users/3
            title: Anakin Skywalker
          userPreferences:
            href: /api/v3/users/3/preferences
          workPackages:
            href: /api/v3/work_packages
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
